[package]
name = "day12"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.12.0"
minisat = "0.4.4"
rayon = "1.8.0"
rust = "0.0.1"
time-graph = "0.3.1"
